[platformio]
default_envs = nucleo_g474re

[env]
build_flags =
  -Wall
  -Wextra
  -Werror
  -D OOMWOO_PROTOCOL_VERSION=2

[env:nucleo_g474re]
platform = ststm32@19.7.0
board = nucleo_g474re
framework = arduino
monitor_speed = 115200
upload_protocol = stlink

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<oomwoo_protocol.c>
