#!/usr/bin/env python3
"""Generate the C command-gate conformance header from the vendored corpus.

This consumes the language-neutral accept/reject corpus authored upstream
(makerspet/oomwoo, contributions/io-board-interface/smailzhu) and emits a C
header that ``tests/command_gate_conformance.c`` runs against this repo's
``oomwoo_cpu_ingress_validate_frame``. If the C gate ever disagrees with an
authored outcome, the conformance test fails -- that is the cross-repo drift
check.

The corpus is *vendored* (a checked-in copy), so its integrity is pinned: the
generator refuses to run unless the file's SHA-256 matches ``EXPECTED_SHA256``.
Update the pin deliberately when syncing a newer upstream revision.

Usage:
    generate_gate_vectors.py           # (re)write the generated header
    generate_gate_vectors.py --check   # fail if the committed header is stale
"""

import argparse
import hashlib
import json
import pathlib
import re

# Names are emitted verbatim into a C string literal, so keep them to a safe set.
_NAME_RE = re.compile(r"^[A-Za-z0-9_]+$")

ROOT = pathlib.Path(__file__).resolve().parents[1]
CORPUS = ROOT / "tests" / "conformance" / "command_gate_vectors_v1.json"
OUTPUT = ROOT / "tests" / "generated" / "oomwoo_command_gate_vectors_v1.h"

# Provenance of the vendored corpus (pin deliberately when syncing upstream).
SOURCE_REPO = "makerspet/oomwoo"
SOURCE_PATH = "contributions/io-board-interface/smailzhu/conformance/command_gate_vectors_v1.json"
SOURCE_REF = "commit d83c13f (feat/command-gate-oracle, PR #70)"
EXPECTED_SHA256 = "a97e246c9a64b95245e11cf43712eaf4ad725830d460e44c715503468d8db0ea"
EXPECTED_COUNT = 57

# Corpus reason string -> firmware ingress result enum.
_REASON_TO_ENUM = {
    "OK": "OOMWOO_CPU_INGRESS_OK",
    "BAD_VERSION": "OOMWOO_CPU_INGRESS_BAD_VERSION",
    "UNKNOWN_TYPE": "OOMWOO_CPU_INGRESS_UNKNOWN_TYPE",
    "WRONG_DIRECTION": "OOMWOO_CPU_INGRESS_WRONG_DIRECTION",
    "WRONG_PAYLOAD_LENGTH": "OOMWOO_CPU_INGRESS_WRONG_PAYLOAD_LENGTH",
    "VALUE_OUT_OF_RANGE": "OOMWOO_CPU_INGRESS_VALUE_OUT_OF_RANGE",
}

MAX_WIRE_PAYLOAD = 512


def _fail(message):
    raise SystemExit(f"generate_gate_vectors: {message}")


def load_corpus():
    """Read, integrity-check, and validate the vendored corpus."""
    if not CORPUS.exists():
        _fail(f"missing vendored corpus {CORPUS}")
    raw = CORPUS.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_SHA256:
        _fail(
            "vendored corpus SHA-256 mismatch (possible silent replacement):\n"
            f"  expected {EXPECTED_SHA256}\n  actual   {digest}\n"
            "If this is an intended upstream sync, update EXPECTED_SHA256."
        )

    doc = json.loads(raw)
    if doc.get("schema_version") != 1:
        _fail(f"unexpected schema_version {doc.get('schema_version')}")
    if doc.get("targets_contract", {}).get("wire_version") != 1:
        _fail("corpus does not target wire_version 1")

    vectors = doc["vectors"]
    if len(vectors) != EXPECTED_COUNT:
        _fail(f"expected {EXPECTED_COUNT} vectors, found {len(vectors)}")

    names = set()
    for v in vectors:
        name = v.get("name", "<unnamed>")
        if not isinstance(name, str) or not _NAME_RE.match(name):
            _fail(f"vector name {name!r} must match [A-Za-z0-9_]+ (emitted into C)")
        if name in names:
            _fail(f"duplicate vector name {name}")
        names.add(name)
        if not (0 <= v["message_type"] <= 0xFFFF):
            _fail(f"{name}: message_type out of range")
        if not (0 <= v["version"] <= 0xFF):
            _fail(f"{name}: version out of range")
        hexstr = v["payload_hex"]
        if len(hexstr) % 2 != 0:
            _fail(f"{name}: odd-length payload_hex")
        payload = bytes.fromhex(hexstr)
        if len(payload) > MAX_WIRE_PAYLOAD:
            _fail(f"{name}: payload longer than wire limit")
        if v["expect"] not in ("OK", "REJECT"):
            _fail(f"{name}: bad expect {v['expect']}")
        if v["reason"] not in _REASON_TO_ENUM:
            _fail(f"{name}: unsupported reason {v['reason']}")
        if (v["expect"] == "OK") != (v["reason"] == "OK"):
            _fail(f"{name}: expect/reason disagree")
    return doc, digest


def render():
    doc, digest = load_corpus()
    vectors = doc["vectors"]
    max_payload = max((len(bytes.fromhex(v["payload_hex"])) for v in vectors), default=0)
    array_len = max(max_payload, 1)  # zero-length arrays are illegal in ISO C

    lines = [
        "/* AUTO-GENERATED by tools/generate_gate_vectors.py -- DO NOT EDIT. */",
        f"/* Vendored corpus: {SOURCE_REPO} {SOURCE_REF} */",
        f"/*   {SOURCE_PATH} */",
        f"/*   sha256 {digest} */",
        "#ifndef OOMWOO_COMMAND_GATE_VECTORS_V1_H",
        "#define OOMWOO_COMMAND_GATE_VECTORS_V1_H",
        "",
        "#include <stdint.h>",
        "",
        '#include "oomwoo_cpu_ingress.h"',
        "",
        f"#define OOMWOO_COMMAND_GATE_VECTOR_MAX_PAYLOAD {array_len}u",
        "",
        "typedef struct {",
        "  const char *name;",
        "  uint16_t message_type;",
        "  uint8_t version;",
        "  uint16_t payload_length;",
        "  uint8_t payload[OOMWOO_COMMAND_GATE_VECTOR_MAX_PAYLOAD];",
        "  oomwoo_cpu_ingress_result_t expected;",
        "} oomwoo_command_gate_vector_t;",
        "",
        "static const oomwoo_command_gate_vector_t OOMWOO_COMMAND_GATE_VECTORS[] = {",
    ]
    for v in vectors:
        payload = bytes.fromhex(v["payload_hex"])
        if payload:
            init = "{" + ", ".join(f"0x{b:02x}u" for b in payload) + "}"
        else:
            init = "{0}"
        lines.append(
            f'  {{ "{v["name"]}", 0x{v["message_type"]:04x}u, {v["version"]}u, '
            f'{len(payload)}u, {init}, {_REASON_TO_ENUM[v["reason"]]} }},'
        )
    lines += [
        "};",
        "",
        f"#define OOMWOO_COMMAND_GATE_VECTOR_COUNT {len(vectors)}u",
        "",
        "#endif /* OOMWOO_COMMAND_GATE_VECTORS_V1_H */",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed header is stale")
    args = parser.parse_args()

    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "generated command gate vectors are stale; run "
                "python3 tools/generate_gate_vectors.py"
            )
        print(f"command gate vector fixture is current ({EXPECTED_COUNT} vectors)")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({EXPECTED_COUNT} vectors)")


if __name__ == "__main__":
    main()
